name: CI (Markdown)

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v2
        with:
          files: |
            "**/*.md"
  markdown-link-check:
    name: Markdown links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruzickap/action-my-markdown-link-checker@v1
        with:
          search_paths: |
            /
            /docs/
