name: CI (Markdown)

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v2
        with:
          files: |
            "**/*.md"
  linkinator:
    name: linkinator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "**/*.md"
          linksToSkip: "https://crates.io/crates/rerun"
